server:
  port: 8080

spring:
#  application:
#    name: buxiban_api
  datasource:
    url: jdbc:mysql://localhost:3306/buxiban_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    auto: true
    proxy-target-class: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 0
#    timeout: 1000 #ms
debug: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mp console sql
    map-underscore-to-camel-case: true
  type-aliases-package: com.buxiban.**.entity
  mapper-locations: classpath:mapper/**/*Mapper.xml


